Rename everything called 'connector' to 'catalog'
Teradata/presto-admin pull request #2
Opened 2016-11-15 22:07 UTC by rschlussel

* rename the config directory from 'connectors' to 'catalog'
* rename the command from 'connector' to 'catalog'
* rename other usages of the word 'connector' to 'catalog' where correct
  to have consistent nomenclature throughout

I tried splitting this up into three different commits, but it was pretty hard to disentangle everything with the file renames.  I hope it's easy enough to review as is.

This commit is on top of the patch to change the default directories, so I'll have to wait until that goes in to merge this, but for review purposes it's independent.

2016-11-15 22:37 UTC, anusudarsan requested changes
Are you also going to update the docs for this?

2016-11-15 22:37 UTC, anusudarsan commented on packaging/install-prestoadmin.template
> +CATALOG_DIR=$CONF_DIR/catalog
should we name this directory "catalogs" to be consistent with connectors?

2016-11-15 22:38 UTC, rschlussel-zz commented on packaging/install-prestoadmin.template
> +CATALOG_DIR=$CONF_DIR/catalog
we're calling it catalog to match the presto directory that has all the catalog configs.

2016-11-15 23:05 UTC, rschlussel commented
Added docs.  They're going to overlap a bit with your docs work because of the path changes.

2016-11-16 13:43 UTC, anusudarsan reviewed
LGTM mod one question. Also, the travis failure looks unrelated?

2016-11-16 13:43 UTC, anusudarsan commented on docs/presto-admin-commands.rst
> +To add a jmx catalog, create a file
should we call jmx, tpch etc as connectors instead? That is how presto calls it, right? For eg: below(line 48) for Custom , we call it a connector. Also applies to the rest of this PR where we refer to tpch/jmx etc.

2016-11-16 15:30 UTC, rschlussel commented on docs/presto-admin-commands.rst
> +To add a jmx catalog, create a file
Sure that makes sense.

2016-11-16 15:32 UTC, rschlussel commented
yeah looks like the presto server just wasn't started yet.  The other build passed

2016-11-16 17:11 UTC, rschlussel commented
updated the docs

2016-11-16 17:24 UTC, anusudarsan approved these changes
LGTM mod comments

2016-11-16 17:24 UTC, anusudarsan commented on docs/installation/presto-catalog-installation.rst
> +In Presto, connector catalogs allow you to access different data sources -- e.g.,
In Presto, connectors?

2016-11-16 17:24 UTC, anusudarsan commented on docs/installation/presto-catalog-installation.rst
> +To add a Hive catalog:
Hive connector

2016-11-16 17:24 UTC, anusudarsan commented on docs/installation/presto-catalog-installation.rst
> +You may need to add additional properties for the Hive catalog to work properly, such as if your Hadoop cluster
Hive connector?

2016-11-16 17:24 UTC, anusudarsan commented on docs/installation/presto-cli-installation.rst
> +3. By default, ``presto-admin`` configures a TPC-H catalog, which generates TPC-H data on-the-fly.
TPC-H connector

2016-11-16 17:55 UTC, rschlussel-zz commented on docs/installation/presto-cli-installation.rst
> +3. By default, ``presto-admin`` configures a TPC-H catalog, which generates TPC-H data on-the-fly.
I think catalog is better here because we're talking about the thing you would specify for the cli.

2016-11-16 17:55 UTC, rschlussel commented on docs/installation/presto-catalog-installation.rst
> +To add a Hive catalog:
done

2016-11-16 17:55 UTC, rschlussel-zz commented on docs/installation/presto-catalog-installation.rst
> +In Presto, connector catalogs allow you to access different data sources -- e.g.,
done

2016-11-16 17:56 UTC, rschlussel commented on docs/installation/presto-catalog-installation.rst
> +You may need to add additional properties for the Hive catalog to work properly, such as if your Hadoop cluster
done

2016-11-22 17:25 UTC, rschlussel commented
merged

2016-11-22 17:25 UTC, closed without merging